name: Build CLI NPM packages

on:
  # pull_request:
  push:
    branches: [ main ]
    paths:
      - 'cli/**'
      - 'server/schema.graphql'

jobs:
  build:
    runs-on: ubuntu-18.04

    defaults:
      run:
        working-directory: cli
      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.3.1'
          cache: 'yarn'

      - name: Yarn install
        working-directory: packages/graphql
        run: yarn install

      - name: Yarn build
        working-directory: packages/graphql
        run: yarn build

      - name: Yarn publish
        run: yarn publish
        working-directory: packages/graphql
        env:
          NPM_TOKEN: ${{ secrets.TYPESHAMAN_NPM }}