name: Build npm package

on:
  push:
    branches: [ main ]
    paths:
      - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    defaults:
      run:
        working-directory: cli
    env:
      TYPESHAMAN_NPM: ${{ secrets.TYPESHAMAN_NPM }}
      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.3.0'
          cache: 'yarn'

      - name: Yarn install
        working-directory: packages/graphql
        run: yarn install

      - name: Yarn build
        working-directory: packages/graphql
        run: yarn build

      - name: Yarn publish
        run: yarn publish
        working-directory: packages/graphql